CCpp LMD Librería DCC++ para Arduino

Que es y para que sirve DCCpp LMD?

DCCpp LMD es una adapatación de la librería DCCpp. Diseñada para placa Arduino MEGA cuenta con diferentes añadidos como pantalla Oled, sonido y multiples puertos seriales. Con esta versión podemos utilizar todos los puertos al mismo tiempo para mandar o recibir los comandos de la central.



<strong>
  
*- Pantalla Oled con librería U8G2lib

*- Serial → PC

*- Serial1 → Wifi

*- Serial2 → Bluetooth

*- Serial3 → Serial Auxiliar

*- Sonido en pin 6
  
</strong>



== License ==

Copyright (c) 2017/2020 Locoduino.org. All right reserved.
Copyright (c) 2017/2020 Thierry Paris.  All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
